name: CI .NET - Pruebas NUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore ./Pruebas.sln

      - name: Compilar solución
        run: dotnet build ./Pruebas.sln --configuration Release --no-restore

      - name: Ejecutar pruebas unitarias
        run: dotnet test ./UnitTestProject1/UnitTestProject1.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

      - name: Subir resultados de pruebas
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ResultadosTest
          path: '**/TestResults/*.trx'